### ISSUE TITLE
Wallet extension eror

### ISSUE THREAD

**Issue by abraham-yusuf** [initia-labs/initia#158]
**Describe the bug**
Unexpected Application Error!
Attempting to use a disconnected port object
Error: Attempting to use a disconnected port object
    at chrome-extension://ffbceckpkpbcmgiaehlloocglmijnpmp/assets/index-B6mvDnej.js:313155:10
    at new Promise (<anonymous>)
    at request$1 (chrome-extension://ffbceckpkpbcmgiaehlloocglmijnpmp/assets/index-B6mvDnej.js:313139:10)
    at Object.queryFn (chrome-extension://ffbceckpkpbcmgiaehlloocglmijnpmp/assets/index-B6mvDnej.js:313211:26)
    at Object.fetchFn [as fn] (chrome-extension://ffbceckpkpbcmgiaehlloocglmijnpmp/assets/index-B6mvDnej.js:14050:27)
    at run (chrome-extension://ffbceckpkpbcmgiaehlloocglmijnpmp/assets/index-B6mvDnej.js:13675:31)
    at createRetryer (chrome-extension://ffbceckpkpbcmgiaehlloocglmijnpmp/assets/index-B6mvDnej.js:13723:5)
    at Query.fetch (chrome-extension://ffbceckpkpbcmgiaehlloocglmijnpmp/assets/index-B6mvDnej.js:14086:20)
    at QueryObserver.executeFetch (chrome-extension://ffbceckpkpbcmgiaehlloocglmijnpmp/assets/index-B6mvDnej.js:15212:37)
    at QueryObserver.fetch (chrome-extension://ffbceckpkpbcmgiaehlloocglmijnpmp/assets/index-B6mvDnej.js:15202:17)

**Screenshots**
![Screenshot_2024-05-15-20-26-13-90_d4b821f22c36211daa9077338f9854d0.jpg](https://github.com/initia-labs/initia/assets/76843145/a92e301d-0d6d-4e0a-839b-904179226621)

**Smartphone :**
 - Device: [Oppo Reno 4F]
 - OS: [Android 12]
 - Browser [Mises Browser ]
 - Version [4240xxxxx]

**Additional context**
Always eror when stay in extension up 15 seconds

**Comment by beer-1** [comment]
This is not chain related issue.
