### ISSUE TITLE
panic: version does not exist

### ISSUE THREAD

**Issue by hail100** [initia-labs/initia#162]
Version:  initiad v0.2.12
How to deal with error:
````
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]: 9:11AM INF Closing application.db module=server
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]: 9:11AM INF Closing snapshots/metadata.db module=server
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]: panic: version does not exist
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]: goroutine 1 [running]:
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]: cosmossdk.io/store/iavl.(*Store).Commit(0xc002045770?)
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]:         cosmossdk.io/store@v1.1.0/iavl/store.go:128 +0xd7
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]: cosmossdk.io/store/rootmulti.commitStores(0x22af4, 0xc001ea8600, 0xc0003dcea0)
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]:         cosmossdk.io/store@v1.1.0/rootmulti/store.go:1196 +0x158
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]: cosmossdk.io/store/rootmulti.(*Store).Commit(0xc002472e00)
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]:         cosmossdk.io/store@v1.1.0/rootmulti/store.go:482 +0x1a5
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]: github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Commit(0xc0002c9b08)
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]:         github.com/cosmos/cosmos-sdk@v0.50.6/baseapp/abci.go:932 +0x2e2
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]: github.com/cosmos/cosmos-sdk/server.cometABCIWrapper.Commit(...)
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]:         github.com/cosmos/cosmos-sdk@v0.50.6/server/cmt_abci.go:56
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]: github.com/cometbft/cometbft/abci/client.(*localClient).Commit(0x20?, {0x41329a0?, 0x61490e0?}, 0xc008a23c60?)
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]:         github.com/cometbft/cometbft@v0.38.7/abci/client/local_client.go:113 +0xcd
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]: github.com/cometbft/cometbft/proxy.(*appConnConsensus).Commit(0xc00260ff38, {0x41329a0, 0x61490e0})
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]:         github.com/cometbft/cometbft@v0.38.7/proxy/app_conn.go:109 +0x168
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]: github.com/cometbft/cometbft/state.(*BlockExecutor).Commit(_, {{{0xb, 0x0}, {0xc000f0b0e8, 0x6}}, {0xc000f0b130, 0xc}, 0x1, 0x22af4, {{0xc000f09ea0, ...}, ...}, ...}, ...)
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]:         github.com/cometbft/cometbft@v0.38.7/state/execution.go:393 +0x213
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]: github.com/cometbft/cometbft/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc000f0b0e8, 0x6}}, {0xc000f0b130, 0xc}, 0x1, 0x22af4, {{0xc000f09ea0, ...}, ...}, ...}, ...)
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]:         github.com/cometbft/cometbft@v0.38.7/state/execution.go:279 +0xfb0
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]: github.com/cometbft/cometbft/consensus.(*Handshaker).replayBlock(_, {{{0xb, 0x0}, {0xc000f0b0e8, 0x6}}, {0xc000f0b130, 0xc}, 0x1, 0x22af3, {{0xc0028a40a0, ...}, ...}, ...}, ...)
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]:         github.com/cometbft/cometbft@v0.38.7/consensus/replay.go:534 +0x24e
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]: github.com/cometbft/cometbft/consensus.(*Handshaker).ReplayBlocksWithContext(_, {_, _}, {{{0xb, 0x0}, {0xc000f0b0e8, 0x6}}, {0xc000f0b130, 0xc}, 0x1, ...}, ...)
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]:         github.com/cometbft/cometbft@v0.38.7/consensus/replay.go:433 +0x77a
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]: github.com/cometbft/cometbft/consensus.(*Handshaker).HandshakeWithContext(0xc008a253f0, {0x41328f8, 0xc003823360}, {0x4156380, 0xc0010fc9a0})
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]:         github.com/cometbft/cometbft@v0.38.7/consensus/replay.go:274 +0x425
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]: github.com/cometbft/cometbft/node.doHandshake({_, _}, {_, _}, {{{0xb, 0x0}, {0xc000f0b0e8, 0x6}}, {0xc000f0b130, 0xc}, ...}, ...)
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]:         github.com/cometbft/cometbft@v0.38.7/node/setup.go:182 +0x1a9
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]: github.com/cometbft/cometbft/node.NewNodeWithContext({0x41328f8, 0xc003823360}, 0xc002474dc0, {0x410d470, 0xc003766500}, 0xc001c7f890, {0x40f4440, 0xc000915140}, 0xc0013d4258, 0x3a098f0, ...)
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]:         github.com/cometbft/cometbft@v0.38.7/node/node.go:359 +0x5b7
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]: github.com/cosmos/cosmos-sdk/server.startCmtNode({0x41328f8, 0xc003823360}, 0xc002474dc0, {0x4178588, 0xc0023dc008}, 0xc000139d80)
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]:         github.com/cosmos/cosmos-sdk@v0.50.6/server/start.go:377 +0x42f
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]: github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{{0xc002852250, 0x6}, 0x0, {0xc002852660, 0x6}, {0xc002852deb, 0x3}, {0x3648541, 0x2}, ...}, ...}, ...)
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]:         github.com/cosmos/cosmos-sdk@v0.50.6/server/start.go:323 +0x17c
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]: github.com/cosmos/cosmos-sdk/server.start(_, {{0x0, 0x0, 0x0}, {0x415a658, 0xc001dd5d10}, 0x0, {0xc001d2bf30, 0xc}, {0x4178650, ...}, ...}, ...)
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]:         github.com/cosmos/cosmos-sdk@v0.50.6/server/start.go:240 +0x2c7
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]: github.com/cosmos/cosmos-sdk/server.StartCmdWithOptions.func2.1()
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]:         github.com/cosmos/cosmos-sdk@v0.50.6/server/start.go:198 +0x63
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]: github.com/cosmos/cosmos-sdk/server.wrapCPUProfile(0xc000139d80, 0xc000d9f9f8)
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]:         github.com/cosmos/cosmos-sdk@v0.50.6/server/start.go:570 +0x1b3
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]: github.com/cosmos/cosmos-sdk/server.StartCmdWithOptions.func2(0xc00186ef08, {0x61490e0?, 0x0?, 0x0?})
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]:         github.com/cosmos/cosmos-sdk@v0.50.6/server/start.go:197 +0x212
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]: github.com/spf13/cobra.(*Command).execute(0xc00186ef08, {0x61490e0, 0x0, 0x0})
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]:         github.com/spf13/cobra@v1.8.0/command.go:983 +0xaca
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]: github.com/spf13/cobra.(*Command).ExecuteC(0xc0017fac08)
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]:         github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]: github.com/spf13/cobra.(*Command).Execute(...)
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]:         github.com/spf13/cobra@v1.8.0/command.go:1039
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]: github.com/spf13/cobra.(*Command).ExecuteContext(...)
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]:         github.com/spf13/cobra@v1.8.0/command.go:1032
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]: github.com/cosmos/cosmos-sdk/server/cmd.Execute(0xc0017fac08, {0x34fb249, 0x6}, {0xc001292f60, 0xd})
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]:         github.com/cosmos/cosmos-sdk@v0.50.6/server/cmd/execute.go:34 +0x187
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]: main.main()
May 16 09:11:29 vmi1658405.contaboserver.net initiad[1620028]:         github.com/initia-labs/initia/cmd/initiad/main.go:15 +0x3b
May 16 09:11:29 vmi1658405.contaboserver.net systemd[1]: initia.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 16 09:11:29 vmi1658405.contaboserver.net systemd[1]: initia.service: Failed with result 'exit-code'.
````

**Comment by beer-1** [comment]
Thanks for reporting this, btw what was the case? 

You met this error after restarting or unexpected shutdown?

**Comment by beer-1** [comment]
closing the issue due to no activity
